//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.CASE_CATEGORIES = new HashSet<CASE_CATEGORIES>();
            this.CASE_COMORBIDITY = new HashSet<CASE_COMORBIDITY>();
            this.CASE_REFERENCES = new HashSet<CASE_REFERENCES>();
            this.CASE_QUESTIONS = new HashSet<CASE_QUESTIONS>();
        }
    
        public decimal CASE_ID { get; set; }
        public System.DateTime CASE_START_DATE { get; set; }
        public string CASE_DESCRIBTION { get; set; }
        public decimal REQUESTER_ID { get; set; }
        public string CASE_TYPE { get; set; }
        public string MRN { get; set; }
        public string NAME { get; set; }
        public string AGE { get; set; }
        public string GENDER { get; set; }
        public string PREGNANT_OR_NOT { get; set; }
        public string PREGNANT_WEEK { get; set; }
        public string ALLERGY_HISTORY { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string DIAGNOSIS { get; set; }
        public string ELECTROLYTES { get; set; }
        public string LIVER_FUNCTION { get; set; }
        public string LABORATORY_RESULT { get; set; }
        public string SERUM_CREATININE { get; set; }
        public string MEDICATIONS { get; set; }
        public string RELATED_SINGS { get; set; }
        public string HAS_MRN_OR_NOT { get; set; }
        public string URGENCY { get; set; }
        public string ANSWER { get; set; }
        public string RESEARCHER_NAME { get; set; }
        public string ANSWER_GIVEN { get; set; }
        public string NOT_REACHABLE_COMMENT { get; set; }
        public Nullable<decimal> RECEIVER_ID { get; set; }
        public string RECEIVER_NAME { get; set; }
        public string CONTACT_ATTEMPT { get; set; }
        public string CASE_STATUS { get; set; }
        public string IS_DIFFER { get; set; }
        public Nullable<System.DateTime> CASE_END_DATE { get; set; }
        public Nullable<decimal> TIME_SPAN_DAY { get; set; }
        public Nullable<decimal> TIME_SPAN_MINUTES { get; set; }
        public Nullable<decimal> TIME_SPAN_HOUR { get; set; }
        public string CURRENT_STAGE { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string ULTIMATE_QUESTION { get; set; }
        public string ULTIMATE_CATEGORY { get; set; }
    
        public virtual ICollection<CASE_CATEGORIES> CASE_CATEGORIES { get; set; }
        public virtual ICollection<CASE_COMORBIDITY> CASE_COMORBIDITY { get; set; }
        public virtual ICollection<CASE_REFERENCES> CASE_REFERENCES { get; set; }
        public virtual USER USER { get; set; }
        public virtual REQUESTER REQUESTER { get; set; }
        public virtual ICollection<CASE_QUESTIONS> CASE_QUESTIONS { get; set; }
    }
}
