//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_REFERENCES
    {
        public decimal CASE_ID { get; set; }
        public decimal REFERENCE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string OTHER_REFRENSES { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual REFERENCE REFERENCE { get; set; }
    }
}
