//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Model : DbContext
    {
        public DB_Model()
            : base("name=DB_Model")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CASE_CATEGORIES> CASE_CATEGORIES { get; set; }
        public DbSet<CASE_COMORBIDITY> CASE_COMORBIDITY { get; set; }
        public DbSet<CASE_REFERENCES> CASE_REFERENCES { get; set; }
        public DbSet<Case> CASES { get; set; }
        public DbSet<PERMISSION> PERMISSIONS { get; set; }
        public DbSet<REGION> REGIONS { get; set; }
        public DbSet<REQUESTER> REQUESTERS { get; set; }
        public DbSet<ROLE> ROLES { get; set; }
        public DbSet<USER> USERS { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public DbSet<CASE_QUESTIONS> CASE_QUESTIONS { get; set; }
        public DbSet<REFERENCE> REFERENCES { get; set; }
        public DbSet<CATEGORy> CATEGORIES { get; set; }
        public DbSet<COMORBIDITY> COMORBIDITies { get; set; }
        public DbSet<MULTIPLE_CHOICE> MULTIPLE_CHOICE { get; set; }
        public DbSet<QUESTION> QUESTIONS { get; set; }
        public DbSet<ROLE_PERMISSIONS> ROLE_PERMISSIONS { get; set; }
        public DbSet<USER_ROLE> USER_ROLE { get; set; }
    }
}
