//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIPLE_CHOICE
    {
        public MULTIPLE_CHOICE()
        {
            this.CASE_QUESTIONS = new HashSet<CASE_QUESTIONS>();
        }
    
        public decimal CHOICE_ID { get; set; }
        public string CHOICE_NAM { get; set; }
        public decimal QUESTION_ID { get; set; }
        public Nullable<decimal> DISPLAY_ORDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
        public string VISIBILITY_STATUS { get; set; }
    
        public virtual ICollection<CASE_QUESTIONS> CASE_QUESTIONS { get; set; }
        public virtual USER USER { get; set; }
        public virtual QUESTION QUESTION { get; set; }
    }
}
