//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public PERMISSION()
        {
            this.ROLE_PERMISSIONS = new HashSet<ROLE_PERMISSIONS>();
        }
    
        public decimal PERMISSION_ID { get; set; }
        public string PERMISSION_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public string TYPE { get; set; }
        public string PERMISSION_DESCRIPTION { get; set; }
    
        public virtual ICollection<ROLE_PERMISSIONS> ROLE_PERMISSIONS { get; set; }
    }
}
