//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public QUESTION()
        {
            this.CASE_QUESTIONS = new HashSet<CASE_QUESTIONS>();
            this.MULTIPLE_CHOICE = new HashSet<MULTIPLE_CHOICE>();
        }
    
        public decimal QUESTION_ID { get; set; }
        public string QUESTION1 { get; set; }
        public decimal CATEGORY_ID { get; set; }
        public string ANSWER_TYPE { get; set; }
        public string VISIBILITY_STATUS { get; set; }
        public string DEFAULT_QUESTION { get; set; }
        public Nullable<decimal> DISPLAY_ORDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual ICollection<CASE_QUESTIONS> CASE_QUESTIONS { get; set; }
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual ICollection<MULTIPLE_CHOICE> MULTIPLE_CHOICE { get; set; }
        public virtual USER USER { get; set; }
    }
}
