//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCE
    {
        public REFERENCE()
        {
            this.CASE_REFERENCES = new HashSet<CASE_REFERENCES>();
        }
    
        public decimal REFERENCE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string VISIBILIT_STATUS { get; set; }
        public Nullable<decimal> DISPLAY_ORDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual ICollection<CASE_REFERENCES> CASE_REFERENCES { get; set; }
        public virtual USER USER { get; set; }
    }
}
