//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.DEPARTMENTS = new HashSet<DEPARTMENT>();
        }
    
        public decimal REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
        public string VISIBILITY_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<DEPARTMENT> DEPARTMENTS { get; set; }
    }
}
