//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUESTER
    {
        public REQUESTER()
        {
            this.CASES = new HashSet<Case>();
        }
    
        public decimal REQUESTER_ID { get; set; }
        public string REQUESTER_NAME { get; set; }
        public string CONTACT { get; set; }
        public string CALLING_FROM { get; set; }
        public decimal DEPARTMENT_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual ICollection<Case> CASES { get; set; }
        public virtual USER USER { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
