//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_PERMISSIONS
    {
        public decimal PERMISSION_ID { get; set; }
        public decimal ROLE_ID { get; set; }
        public string COLUMN1 { get; set; }
    
        public virtual PERMISSION PERMISSION { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
