//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.ROLE_PERMISSIONS = new HashSet<ROLE_PERMISSIONS>();
            this.USER_ROLE = new HashSet<USER_ROLE>();
        }
    
        public decimal ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<ROLE_PERMISSIONS> ROLE_PERMISSIONS { get; set; }
        public virtual ICollection<USER_ROLE> USER_ROLE { get; set; }
    }
}
