//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.CASES = new HashSet<Case>();
            this.REGIONS = new HashSet<REGION>();
            this.REQUESTERS = new HashSet<REQUESTER>();
            this.ROLES = new HashSet<ROLE>();
            this.DEPARTMENTS = new HashSet<DEPARTMENT>();
            this.REFERENCES = new HashSet<REFERENCE>();
            this.CATEGORIES = new HashSet<CATEGORy>();
            this.COMORBIDITies = new HashSet<COMORBIDITY>();
            this.MULTIPLE_CHOICE = new HashSet<MULTIPLE_CHOICE>();
            this.QUESTIONS = new HashSet<QUESTION>();
            this.USER_ROLE = new HashSet<USER_ROLE>();
        }
    
        public decimal USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<Case> CASES { get; set; }
        public virtual ICollection<REGION> REGIONS { get; set; }
        public virtual ICollection<REQUESTER> REQUESTERS { get; set; }
        public virtual ICollection<ROLE> ROLES { get; set; }
        public virtual ICollection<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual ICollection<REFERENCE> REFERENCES { get; set; }
        public virtual ICollection<CATEGORy> CATEGORIES { get; set; }
        public virtual ICollection<COMORBIDITY> COMORBIDITies { get; set; }
        public virtual ICollection<MULTIPLE_CHOICE> MULTIPLE_CHOICE { get; set; }
        public virtual ICollection<QUESTION> QUESTIONS { get; set; }
        public virtual ICollection<USER_ROLE> USER_ROLE { get; set; }
    }
}
